import { relations, sql } from "drizzle-orm";
import {
  index,
  integer,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

/**
 * Schema for the MUBAS Smart Hostel Booking and Management System.
 *
 * Design notes
 * - Text primary keys: identifiers are generated by the application (e.g. `nyika`,
 *   `al_defton`) so that a QR payload such as `MUBAS-CI:<allocationId>:<code>` stays
 *   readable and stable across environments.
 * - Timestamps are stored as `timestamptz` and surfaced to the UI as ISO strings
 *   (`mode: "string"`), which keeps server components free of date conversion.
 * - Foreign keys carry explicit indexes; every uniqueness rule that the hostel
 *   office depends on (one bed per student per semester, one live application,
 *   one vote per student per ticket) is enforced by a database constraint rather
 *   than only by application code.
 */

const createdAt = () =>
  timestamp("created_at", { withTimezone: true, mode: "string" })
    .notNull()
    .defaultNow();

/* ------------------------------------------------------------------ enums */

export const userRole = pgEnum("user_role", ["student", "admin", "security"]);
export const hostelGender = pgEnum("hostel_gender", ["male", "female", "open"]);
export const campusKind = pgEnum("campus_kind", ["on-campus", "off-campus"]);
export const applicationStatus = pgEnum("application_status", [
  "pending",
  "approved",
  "rejected",
]);
export const allocationStatus = pgEnum("allocation_status", [
  "active",
  "checked-out",
  "released",
]);
export const ticketStatus = pgEnum("ticket_status", ["open", "in-progress", "resolved"]);
export const paymentMethod = pgEnum("payment_method", [
  "airtel-money",
  "tnm-mpamba",
  "bank-transfer",
]);
export const paymentStatus = pgEnum("payment_status", ["paid", "pending", "flagged"]);
export const transferStatus = pgEnum("transfer_status", ["pending", "approved", "rejected"]);
export const complaintStatus = pgEnum("complaint_status", ["new", "acknowledged", "resolved"]);
export const lostFoundKind = pgEnum("lost_found_kind", ["lost", "found"]);
export const inspectionCondition = pgEnum("inspection_condition", ["good", "fair", "poor"]);
export const checkDirection = pgEnum("check_direction", ["in", "out"]);

/* ------------------------------------------------------------------ users */

export const users = pgTable(
  "users",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    email: text("email").notNull(),
    passwordHash: text("password_hash").notNull(),
    role: userRole("role").notNull().default("student"),
    regNumber: text("reg_number"),
    program: text("program"),
    year: integer("year"),
    phone: text("phone"),
    createdAt: createdAt(),
  },
  (table) => [
    uniqueIndex("users_email_key").on(sql`lower(${table.email})`),
    uniqueIndex("users_reg_number_key")
      .on(table.regNumber)
      .where(sql`${table.regNumber} is not null`),
    index("users_role_idx").on(table.role),
  ],
);

/* --------------------------------------------------------------- hostels */

export const hostels = pgTable(
  "hostels",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    gender: hostelGender("gender").notNull().default("open"),
    campus: campusKind("campus").notNull(),
    location: text("location").notNull(),
    description: text("description").notNull(),
    monthlyFee: integer("monthly_fee").notNull(),
    /** Short selling points rendered as chips on the hostel detail screen. */
    amenities: text("amenities")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    photoUrl: text("photo_url"),
    rating: integer("rating"),
    createdAt: createdAt(),
  },
  (table) => [index("hostels_campus_idx").on(table.campus)],
);

/* ----------------------------------------------------------- rooms & beds */

export const rooms = pgTable(
  "rooms",
  {
    id: text("id").primaryKey(),
    hostelId: text("hostel_id")
      .notNull()
      .references(() => hostels.id, { onDelete: "cascade" }),
    number: text("number").notNull(),
    floor: text("floor"),
    createdAt: createdAt(),
  },
  (table) => [
    uniqueIndex("rooms_hostel_number_key").on(table.hostelId, table.number),
    index("rooms_hostel_idx").on(table.hostelId),
  ],
);

export const beds = pgTable(
  "beds",
  {
    id: text("id").primaryKey(),
    roomId: text("room_id")
      .notNull()
      .references(() => rooms.id, { onDelete: "cascade" }),
    label: text("label").notNull(),
    /** Set when a bed is allocated; cleared when the student moves out. */
    occupantId: text("occupant_id").references(() => users.id, { onDelete: "set null" }),
    createdAt: createdAt(),
  },
  (table) => [
    uniqueIndex("beds_room_label_key").on(table.roomId, table.label),
    index("beds_room_idx").on(table.roomId),
    index("beds_occupant_idx").on(table.occupantId),
  ],
);

/* ----------------------------------------------------------- applications */

export const applications = pgTable(
  "applications",
  {
    id: text("id").primaryKey(),
    studentId: text("student_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    hostelId: text("hostel_id")
      .notNull()
      .references(() => hostels.id, { onDelete: "restrict" }),
    semester: text("semester").notNull(),
    status: applicationStatus("status").notNull().default("pending"),
    note: text("note"),
    decidedAt: timestamp("decided_at", { withTimezone: true, mode: "string" }),
    createdAt: createdAt(),
  },
  (table) => [
    // One live application per student per semester (rejected rows may repeat).
    uniqueIndex("applications_student_semester_live_key")
      .on(table.studentId, table.semester)
      .where(sql`${table.status} <> 'rejected'`),
    index("applications_status_idx").on(table.status),
    index("applications_hostel_idx").on(table.hostelId),
  ],
);

/* ------------------------------------------------------------ allocations */

export const allocations = pgTable(
  "allocations",
  {
    id: text("id").primaryKey(),
    studentId: text("student_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    hostelId: text("hostel_id")
      .notNull()
      .references(() => hostels.id, { onDelete: "restrict" }),
    roomId: text("room_id")
      .notNull()
      .references(() => rooms.id, { onDelete: "cascade" }),
    bedId: text("bed_id")
      .notNull()
      .references(() => beds.id, { onDelete: "cascade" }),
    semester: text("semester").notNull(),
    status: allocationStatus("status").notNull().default("active"),
    checkInCode: text("check_in_code").notNull(),
    checkedInAt: timestamp("checked_in_at", { withTimezone: true, mode: "string" }),
    checkedOutAt: timestamp("checked_out_at", { withTimezone: true, mode: "string" }),
    createdAt: createdAt(),
  },
  (table) => [
    uniqueIndex("allocations_check_in_code_key").on(table.checkInCode),
    // A student holds at most one bed per semester, and a bed hosts one student.
    uniqueIndex("allocations_student_semester_key").on(table.studentId, table.semester),
    uniqueIndex("allocations_bed_semester_key").on(table.bedId, table.semester),
    index("allocations_hostel_idx").on(table.hostelId),
    index("allocations_room_idx").on(table.roomId),
    index("allocations_status_idx").on(table.status),
  ],
);

/* --------------------------------------------------------------- payments */

export const payments = pgTable(
  "payments",
  {
    id: text("id").primaryKey(),
    studentId: text("student_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    amount: integer("amount").notNull(),
    method: paymentMethod("method").notNull(),
    payerPhone: text("payer_phone").notNull(),
    reference: text("reference").notNull(),
    semester: text("semester").notNull(),
    status: paymentStatus("status").notNull().default("paid"),
    createdAt: createdAt(),
  },
  (table) => [
    index("payments_student_idx").on(table.studentId),
    index("payments_semester_status_idx").on(table.semester, table.status),
  ],
);

export const receipts = pgTable(
  "receipts",
  {
    id: text("id").primaryKey(),
    paymentId: text("payment_id")
      .notNull()
      .references(() => payments.id, { onDelete: "cascade" }),
    tracking: text("tracking").notNull(),
    issuedAt: timestamp("issued_at", { withTimezone: true, mode: "string" })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    uniqueIndex("receipts_tracking_key").on(table.tracking),
    uniqueIndex("receipts_payment_key").on(table.paymentId),
  ],
);

/** Single-row table holding the receipt sequence, so tracking numbers never collide. */
export const counters = pgTable("counters", {
  name: text("name").primaryKey(),
  value: integer("value").notNull().default(0),
});

/* ------------------------------------------------------------ maintenance */

export const maintenanceTickets = pgTable(
  "maintenance_tickets",
  {
    id: text("id").primaryKey(),
    roomId: text("room_id")
      .notNull()
      .references(() => rooms.id, { onDelete: "cascade" }),
    studentId: text("student_id").references(() => users.id, { onDelete: "set null" }),
    category: text("category").notNull().default("General"),
    description: text("description").notNull(),
    photos: text("photos")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    status: ticketStatus("status").notNull().default("open"),
    createdAt: createdAt(),
  },
  (table) => [
    index("tickets_room_idx").on(table.roomId),
    index("tickets_status_idx").on(table.status),
  ],
);

/** Collective voting: one row per student per ticket. */
export const ticketVotes = pgTable(
  "ticket_votes",
  {
    ticketId: text("ticket_id")
      .notNull()
      .references(() => maintenanceTickets.id, { onDelete: "cascade" }),
    studentId: text("student_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    createdAt: createdAt(),
  },
  (table) => [
    primaryKey({ columns: [table.ticketId, table.studentId], name: "ticket_votes_pkey" }),
    index("ticket_votes_student_idx").on(table.studentId),
  ],
);

export const transferRequests = pgTable(
  "transfer_requests",
  {
    id: text("id").primaryKey(),
    studentId: text("student_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    fromAllocationId: text("from_allocation_id")
      .notNull()
      .references(() => allocations.id, { onDelete: "cascade" }),
    toHostelId: text("to_hostel_id")
      .notNull()
      .references(() => hostels.id, { onDelete: "restrict" }),
    reason: text("reason").notNull(),
    status: transferStatus("status").notNull().default("pending"),
    reviewerNote: text("reviewer_note"),
    createdAt: createdAt(),
  },
  (table) => [
    index("transfers_status_idx").on(table.status),
    index("transfers_student_idx").on(table.studentId),
  ],
);

/**
 * Noise complaints are deliberately anonymous: no student identifier is stored,
 * which is the whole point of the feature.
 */
export const noiseComplaints = pgTable(
  "noise_complaints",
  {
    id: text("id").primaryKey(),
    hostelId: text("hostel_id")
      .notNull()
      .references(() => hostels.id, { onDelete: "cascade" }),
    location: text("location").notNull(),
    description: text("description").notNull(),
    status: complaintStatus("status").notNull().default("new"),
    resolvedAt: timestamp("resolved_at", { withTimezone: true, mode: "string" }),
    createdAt: createdAt(),
  },
  (table) => [index("complaints_hostel_idx").on(table.hostelId)],
);

export const lostFoundItems = pgTable(
  "lost_found_items",
  {
    id: text("id").primaryKey(),
    kind: lostFoundKind("kind").notNull(),
    title: text("title").notNull(),
    description: text("description").notNull(),
    location: text("location").notNull(),
    contact: text("contact").notNull(),
    reporterName: text("reporter_name").notNull(),
    status: text("status").notNull().default("open"),
    createdAt: createdAt(),
  },
  (table) => [index("lost_found_status_idx").on(table.status)],
);

export const inspections = pgTable(
  "inspections",
  {
    id: text("id").primaryKey(),
    roomId: text("room_id")
      .notNull()
      .references(() => rooms.id, { onDelete: "cascade" }),
    inspectorId: text("inspector_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    condition: inspectionCondition("condition").notNull(),
    notes: text("notes").notNull(),
    photos: text("photos")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    createdAt: createdAt(),
  },
  (table) => [index("inspections_room_idx").on(table.roomId)],
);

export const checkEvents = pgTable(
  "check_events",
  {
    id: text("id").primaryKey(),
    allocationId: text("allocation_id")
      .notNull()
      .references(() => allocations.id, { onDelete: "cascade" }),
    type: checkDirection("type").notNull(),
    at: timestamp("at", { withTimezone: true, mode: "string" })
      .notNull()
      .defaultNow(),
    code: text("code").notNull(),
    byId: text("by_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
  },
  (table) => [
    index("check_events_allocation_idx").on(table.allocationId),
    index("check_events_at_idx").on(table.at),
  ],
);

/* --------------------------------------------------------------- relations */

export const hostelsRelations = relations(hostels, ({ many }) => ({
  rooms: many(rooms),
}));

export const roomsRelations = relations(rooms, ({ one, many }) => ({
  hostel: one(hostels, { fields: [rooms.hostelId], references: [hostels.id] }),
  beds: many(beds),
}));

export const bedsRelations = relations(beds, ({ one }) => ({
  room: one(rooms, { fields: [beds.roomId], references: [rooms.id] }),
  occupant: one(users, { fields: [beds.occupantId], references: [users.id] }),
}));

export const usersRelations = relations(users, ({ many }) => ({
  applications: many(applications),
  allocations: many(allocations),
  payments: many(payments),
}));

export const applicationsRelations = relations(applications, ({ one }) => ({
  student: one(users, { fields: [applications.studentId], references: [users.id] }),
  hostel: one(hostels, { fields: [applications.hostelId], references: [hostels.id] }),
}));

export const allocationsRelations = relations(allocations, ({ one }) => ({
  student: one(users, { fields: [allocations.studentId], references: [users.id] }),
  hostel: one(hostels, { fields: [allocations.hostelId], references: [hostels.id] }),
  room: one(rooms, { fields: [allocations.roomId], references: [rooms.id] }),
  bed: one(beds, { fields: [allocations.bedId], references: [beds.id] }),
}));

export const paymentsRelations = relations(payments, ({ one, many }) => ({
  student: one(users, { fields: [payments.studentId], references: [users.id] }),
  receipt: one(receipts),
}));

export const receiptsRelations = relations(receipts, ({ one }) => ({
  payment: one(payments, { fields: [receipts.paymentId], references: [payments.id] }),
}));

export const maintenanceTicketsRelations = relations(maintenanceTickets, ({ one, many }) => ({
  room: one(rooms, { fields: [maintenanceTickets.roomId], references: [rooms.id] }),
  reporter: one(users, { fields: [maintenanceTickets.studentId], references: [users.id] }),
  votes: many(ticketVotes),
}));

export const ticketVotesRelations = relations(ticketVotes, ({ one }) => ({
  ticket: one(maintenanceTickets, {
    fields: [ticketVotes.ticketId],
    references: [maintenanceTickets.id],
  }),
  student: one(users, { fields: [ticketVotes.studentId], references: [users.id] }),
}));

export const transferRequestsRelations = relations(transferRequests, ({ one }) => ({
  student: one(users, { fields: [transferRequests.studentId], references: [users.id] }),
  allocation: one(allocations, {
    fields: [transferRequests.fromAllocationId],
    references: [allocations.id],
  }),
  targetHostel: one(hostels, {
    fields: [transferRequests.toHostelId],
    references: [hostels.id],
  }),
}));

export const noiseComplaintsRelations = relations(noiseComplaints, ({ one }) => ({
  hostel: one(hostels, { fields: [noiseComplaints.hostelId], references: [hostels.id] }),
}));

export const inspectionsRelations = relations(inspections, ({ one }) => ({
  room: one(rooms, { fields: [inspections.roomId], references: [rooms.id] }),
  inspector: one(users, { fields: [inspections.inspectorId], references: [users.id] }),
}));

export const checkEventsRelations = relations(checkEvents, ({ one }) => ({
  allocation: one(allocations, {
    fields: [checkEvents.allocationId],
    references: [allocations.id],
  }),
  officer: one(users, { fields: [checkEvents.byId], references: [users.id] }),
}));

export type UserRow = typeof users.$inferSelect;
export type HostelRow = typeof hostels.$inferSelect;
export type RoomRow = typeof rooms.$inferSelect;
export type BedRow = typeof beds.$inferSelect;
export type ApplicationRow = typeof applications.$inferSelect;
export type AllocationRow = typeof allocations.$inferSelect;
export type PaymentRow = typeof payments.$inferSelect;
export type ReceiptRow = typeof receipts.$inferSelect;
export type MaintenanceTicketRow = typeof maintenanceTickets.$inferSelect;
export type TransferRequestRow = typeof transferRequests.$inferSelect;
export type NoiseComplaintRow = typeof noiseComplaints.$inferSelect;
export type LostFoundItemRow = typeof lostFoundItems.$inferSelect;
export type InspectionRow = typeof inspections.$inferSelect;
export type CheckEventRow = typeof checkEvents.$inferSelect;
export type TicketVoteRow = typeof ticketVotes.$inferSelect;
export type CounterRow = typeof counters.$inferSelect;